export const doctorname = [
    {
        id: 1,
        image: "/images/Doctors.png",
        names: "Rose Francisco, MD",
        label: "HMO",
        specialty: "OB-GYNE",
        rate: "100%",
        clinic: "Metropolitan Medical Center , TeleMedicine Inc.",
        path:"/infoA",
        hospital: "Western Visayas Medical Center",
        address: "Mandurriao, Iloilo City",
        schedule: "Tue and Thu",
        professionalFee: "400.00",
        medCert: "500.00",
        medClearance: "1000.00",
        medAbstract: "750.00"
    },

    {
        id: 2,
        image: "/images/Doctors.png",
        names: "Martin Luther, MD",
        label: "HMOs",
        specialty: "OB-GYNE",
        rate: "100%",
        clinic: "Metropolitan Medical Center , TeleMedicine Inc.",
        path:"/infB",
        hospital: "Western Visayas Medical Center",
        address: "Mandurriao, Iloilo City",
        schedule: "Tue and Thu",
        professionalFee: "400.00",
        medCert: "500.00",
        medClearance: "1000.00",
        medAbstract: "750.00"
    },

    {
        id: 3,
        image: "/images/Doctors.png",
        names: "Ayen Basco, MD",
        label: "HMOf",
        specialty: "OB-GYNE",
        rate: "100%",
        clinic: "Metropolitan Medical Center , TeleMedicine Inc.",
        path:"/infoC",
        hospital: "Western Visayas Medical Center",
        address: "Mandurriao, Iloilo City",
        schedule: "Tue and Thu",
        professionalFee: "400.00",
        medCert: "500.00",
        medClearance: "1000.00",
        medAbstract: "750.00"
    },

    {
        id: 4,
        image: "/images/Doctors.png",
        names: "Lisa Dean Sual, MD",
        label: "HMOgh",
        specialty: "OB-GYNE",
        rate: "100%",
        clinic: "Metropolitan Medical Center , TeleMedicine Inc.",
        path:"/infoD",
        hospital: "Western Visayas Medical Center",
        address: "Mandurriao, Iloilo City",
        schedule: "Tue and Thu",
        professionalFee: "400.00",
        medCert: "500.00",
        medClearance: "1000.00",
        medAbstract: "750.00"
    },

    {
        id: 5,
        image: "/images/Doctors.png",
        names: "Kian Ramose, MD",
        label: "HMO",
        specialty: "OB-GYNE",
        rate: "100%",
        clinic: "Metropolitan Medical Center , TeleMedicine Inc.",
        path:"/infoE",
        hospital: "Western Visayas Medical Center",
        address: "Mandurriao, Iloilo City",
        schedule: "Tue and Thu",
        professionalFee: "400.00",
        medCert: "500.00",
        medClearance: "1000.00",
        medAbstract: "750.00"
    },

    {
        id: 6,
        image: "/images/Doctors.png",
        names: "Estes Liba, MD",
        label: "HMO",
        specialty: "OB-GYNE",
        rate: "100%",
        clinic: "Metropolitan Medical Center , TeleMedicine Inc.",
        path:"/infoF",
        hospital: "Western Visayas Medical Center",
        address: "Mandurriao, Iloilo City",
        schedule: "Tue and Thu",
        professionalFee: "400.00",
        medCert: "500.00",
        medClearance: "1000.00",
        medAbstract: "750.00"
    },

    {
        id: 7,
        image: "/images/Doctors.png",
        names: "Estes Liba, MD",
        label: "HMO",
        specialty: "OB-GYNE",
        rate: "100%",
        clinic: "Metropolitan Medical Center , TeleMedicine Inc.",
        path:"/infoF",
        hospital: "Western Visayas Medical Center",
        address: "Mandurriao, Iloilo City",
        schedule: "Tue and Thu",
        professionalFee: "400.00",
        medCert: "500.00",
        medClearance: "1000.00",
        medAbstract: "750.00"
    },

    {
        id: 8,
        image: "/images/Doctors.png",
        names: "Estes Liba, MD",
        label: "HMO",
        specialty: "OB-GYNE",
        rate: "100%",
        clinic: "Metropolitan Medical Center , TeleMedicine Inc.",
        path:"/infoF",
        hospital: "Western Visayas Medical Center",
        address: "Mandurriao, Iloilo City",
        schedule: "Tue and Thu",
        professionalFee: "400.00",
        medCert: "500.00",
        medClearance: "1000.00",
        medAbstract: "750.00"
    },
]